config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  root to: 'pages#home'

  resources :parkings  do
    resources :bookings, only: [:new, :create]
  end
  resources :bookings, only: [:index, :show, :update, :edit]

  get '/test', to: 'pages#test'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :user
  belongs_to :parking

  validates :start_time, presence: true
  validates :finish_time, presence: true

  def end_time
    finish_time
  end
end

app/models/parking.rb
class Parking < ApplicationRecord
  belongs_to :user
  has_many :bookings

  validates :address, presence: true
  validates :start_time, presence: true
  validates :finish_time, presence: true

  geocoded_by :address
  after_validation :geocode, if: :will_save_change_to_address?

  include PgSearch
  pg_search_scope :search_by_city,
    against: :city,
    using: {
      tsearch: { prefix: true }
    }

  mount_uploader :photo, PhotoUploader
end

app/models/simple_calendar.rb
class SimpleCalendar::BusinessWeekCalendar < SimpleCalendar::Calendar

  private

  def date_range
    @parking = Parking.find(params[:id])
    beginning = @parking.start_time
    ending    = @parking.finish_time
    (beginning..ending).to_a
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :bookings, dependent: :destroy
  has_many :parkings, dependent: :destroy
  has_many :own_parkings_bookings, through: :parkings, source: :bookings
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :authenticate_user!

  include Pundit

  # Pundit: white-list approach.
  after_action :verify_authorized, except: :index, unless: :skip_pundit?
  after_action :verify_policy_scoped, only: :index, unless: :skip_pundit?

  # Uncomment when you *really understand* Pundit!
  # rescue_from Pundit::NotAuthorizedError, with: :user_not_authorized
  # def user_not_authorized
  #   flash[:alert] = "You are not authorized to perform this action."
  #   redirect_to(root_path)
  # end

  private

  def skip_pundit?
    devise_controller? || params[:controller] =~ /(^(rails_)?admin)|(^pages$)/
  end
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  before_action :set_booking, only: [:edit, :update]

  def index
    @requested_bookings = policy_scope(Booking)
    @own_parkings_bookings = current_user.own_parkings_bookings
  end

  def new
    @parking = Parking.find(params[:id])
    @booking = Booking.new
    authorize @parking
    authorize @booking
  end

  def show
    @booking = Booking.find(params[:id])
    authorize @booking
  end

  def create
    @parking = Parking.find(params[:parking_id])
    @booking = Booking.new(booking_params)
    @booking.parking = @parking
    @booking.user = current_user
    authorize @booking
    # user should not be allowed to create/book the space if booking already exists

    if @booking.valid? && verify_dates(@booking, @parking)
      @booking.save
      flash[:notice] = "great, you have successfully booked your parking space"
      redirect_to booking_path(@booking)
    else
      flash[:alert] = "oops, this space is not available for those dates, dude."
      render :new
    end
  end

  def edit
    authorize @booking
  end

  def update
    authorize @booking
    if @booking.update(booking_params) && @booking.status == "accepted"
      flash[:notice] = "booking accepted"
      redirect_to booking_path(@booking)
    elsif @booking.update(booking_params) && @booking.status == "declined"
      flash[:alert] = "booking rejected"
      redirect_to booking_path(@booking)
    else
      render :show
    end
  end

  private

  def set_booking
    @booking = Booking.find(params[:id])
  end

  def booking_params
    params.require(:booking).permit(:start_time, :finish_time, :status)
  end

  # below gives undefined method: verify_dates Did you mean verify_authorized
  def verify_dates(booking, parking)
    if booking.start_time > parking.start_time && booking.finish_time < parking.finish_time
      desired_booking = [(booking.start_time..booking.finish_time)]
      existing_bookings = parking.bookings.map { |existing_bkng| (existing_bkng.start_time..existing_bkng.finish_time) }
      array_of_ranges = desired_booking + existing_bookings
      true unless Overlaps.find(array_of_ranges).empty?
    end
    false
  end
  # def verify_dates
  #   ('start_time, finish_time').overlaps?('start_time, finish_time')
  # end

  # def verify_dates

  # end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: [:home]

  def home
    # @parking = Parking.new
    @parkings = Parking.all
    @home_parkings = Parking.all.sample(3)
  end

  def test
  end
end

app/controllers/parkings_controller.rb
class ParkingsController < ApplicationController
  before_action :set_parking, only: [:show, :edit, :update, :destroy]

  def index
    if params[:query].present?
      @parkings = policy_scope(Parking).search_by_city(params[:query]).where.not(latitude: nil, longitude: nil)
    else
      @parkings = policy_scope(Parking).where.not(latitude: nil, longitude: nil)
    end

    @markers = @parkings.map do |parking|
      {
        lng: parking.longitude,
        lat: parking.latitude,
        infoWindow: { content: render_to_string(partial: "/parkings/map_window_index", locals: { parking: parking }) }
      }
    end
  end

  def show
    @parking = Parking.find(params[:id])
    @booking = Booking.new
    authorize @parking

    @marker = {
        lng: @parking.longitude,
        lat: @parking.latitude,
        infoWindow: { content: render_to_string(partial: "/parkings/map_window_show", locals: { parking: @parking }) }
    }
    
  end

  def new
    @parking = Parking.new
    authorize @parking
  end

  def create
    @parking = Parking.new(parking_params)
    @parking.user = current_user
    @parking.save
    authorize @parking

    if @parking.save
      flash[:notice] = "great, you have successfully uploaded your parking space"
      redirect_to parking_path(@parking)
    else
      flash[:alert] = "oops, something is wrong, dude."
      render :new
    end
  end

  def edit
    authorize @parking
  end

  def update
    authorize @parking
    if @parking.update(parking_params)
      flash[:notice] = "great, you have successfully edited your parking space"
      redirect_to parking_path(@parking)
    else
      flash[:alert] = "oops, something is wrong, dude."
      render :edit
    end
  end

  def destroy
    authorize @parking
    @parking.delete
    redirect_to parkings_path
  end

  private

  def set_parking
    @parking = Parking.find(params[:id])
  end

  def parking_params
    params.require(:parking).permit(:address, :description, :start_time, :finish_time, :price, :city, :zip_code, :photo)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/bookings/_booking-owner.html.erb
<div id="booking-header">
  <h3>hi <%= current_user.email.split('@')[0] %></h3>
  <h6 class="accent-header">somebody wants your parking space, yay!</h6>
</div>

<div id="booking-content">

  <div id="booking-details">
    <h6><span class="booking">request for:</span></h6>
    <p><%= @booking.parking.address %></p>

    <h6><span class="booking">from:</span></h6>
    <p>from: <%= @booking.start_time.strftime("%Y/%m/%d") %> to <%= @booking.finish_time.strftime("%Y/%m/%d") %></p>

    <h6><span class="booking">total:</span></h6>
    <p><%= @booking.parking.price * (@booking.finish_time.day - @booking.start_time.day) %> $</p>

  </div>

  <div id="booking-owner-actions">
    <% if @booking.status == "pending" %>

      <h6><span class="booking">booking status: pending</span></h6>

      <div class="booking-actions">
         <%= link_to booking_path(@booking, {booking: {status: "accepted"}}), method: :patch do %>
          <i class="fas fa-check"></i>
        <% end %>
         <%= link_to booking_path(@booking, {booking: {status: "declined"}}), method: :patch do %>
          <i class="fas fa-times"></i>
        <% end %>
        <%= link_to booking_path(@booking, {booking: {status: "pending"}}), method: :patch do %>
          <i class="fas fa-question"></i>
        <% end %>
      </div>

    <% elsif @booking.status == "declined" %>

    <h6><span class="booking">booking status: declined</span></h6>

      <div class="booking-actions">
         <%= link_to booking_path(@booking, {booking: {status: "accepted"}}), method: :patch do %>
          <i class="fas fa-check"></i>
        <% end %>
        <%= link_to booking_path(@booking, {booking: {status: "pending"}}), method: :patch do %>
          <i class="fas fa-question"></i>
        <% end %>
      </div>

    <% else @booking.status == "accepted" %>

      <h6><span class="booking">booking status: accepted</span></h6>

      <div class="booking-actions">
         <%= link_to booking_path(@booking, {booking: {status: "declined"}}), method: :patch do %>
          <i class="fas fa-times"></i>
        <% end %>
        <%= link_to booking_path(@booking, {booking: {status: "pending"}}), method: :patch do %>
          <i class="fas fa-question"></i>
        <% end %>
      </div>

    <% end %>

  </div>

</div>

app/views/bookings/_booking-user.html.erb
<div id="booking-header">
  <h3>hi <%= current_user.email.split('@')[0] %></h3>
  <h6 class="accent-header">great, your car found a place to stay!</h6>
</div>

<div id="booking-details">


  <h6>here are the details of your booking</h6>

  <h6><span class="booking">request for:</span></h6>
  <p><%= @booking.parking.address %></p>

  <h6><span class="booking">from:</span></h6>
  <p>from: <%= @booking.start_time.strftime("%Y/%m/%d") %> to <%= @booking.finish_time.strftime("%Y/%m/%d") %></p>

  <h6><span class="booking">total:</span></h6>
  <p><%= @booking.parking.price * (@booking.finish_time.day - @booking.start_time.day) %> $</p>

</div>

<div class="booking-renter-status">
  <% if @booking.status == "pending" %>
    <h6><span class="booking">booking status: pending</span></h6>
<!--   <p class="booking-pending"><i class="fas fa-star"></i>pending</p> -->

  <% elsif @booking.status == "declined" %>
  <h6><span class="booking">booking status: declined</span></h6>
<!--   <p class="booking-declined"><i class="fas fa-times"></i>not okay</p> -->

  <% else @booking.status == "accepted" %>
  <h6><span class="booking">booking status: accepted</span></h6>
  <!-- <p class="booking-accepted"><i class="fas fa-check"></i>okay</p> -->

  <% end %>

</div>

app/views/bookings/_form.html.erb
<%= simple_form_for([@parking, @booking]) do |f| %>
<%= f.input :start_time, label: "start date", as: :datepicker  %>
<%= f.input :finish_time, label: "end date", as: :datepicker%>

<%= f.submit class: 'btn btn-light full-width', value: "Book now" %>
<% end %>

app/views/bookings/create.html.erb
<h1>Bookings#create</h1>
<p>Find me in app/views/bookings/create.html.erb</p>

app/views/bookings/edit.html.erb
<h1>Bookings#edit</h1>
<p>update your booking time</p>

app/views/bookings/index.html.erb
<div class="container">
  <h1> Your Parking Rental Bookings</h1>
  <h4>My requests</h4>
  <ul class="list-group">

      <% @requested_bookings.each do |booking| %>
    <li class="list-group-item d-flex justify-content-between align-items-center">
      <%= booking.parking.user.email %>
      <%= booking.parking.address %>
      <%= booking.start_time.strftime('%Y-%m-%d') %>
      <%= booking.finish_time.strftime('%Y-%m-%d') %>
      <%= link_to 'Details', booking_path(booking) %>
      <span class="badge badge-primary badge-pill">
        <%= booking.status %>
      </span>
    <% end %>
    </li>

    </ul>

  <h4>Booking Requests for your parking space</h4>
    <ul class="list-group">
        <% @own_parkings_bookings.each do |booking| %>
      <li class="list-group-item d-flex justify-content-between align-items-center">
      <%= booking.user.email %>
      <%= booking.parking.address %>
      <%= booking.start_time.strftime('%Y-%m-%d') %>
      <%= booking.finish_time.strftime('%Y-%m-%d') %>
      <%= link_to 'Details', booking_path(booking) %>
      <span class="badge badge-primary badge-pill"><%= booking.status %></span>
      </li>
      <% end %>
    </ul>

</div>

app/views/bookings/new.html.erb
<%= render "form" %>

<!-- links to payment/thank you page -->

app/views/bookings/show.html.erb
<div id="booking-page">
  <div class="container">
    <div class="row">
      <div class="col-xs-10 col-xs-offset-1 col-md-8 col-md-offset-2">

        <div id="booking-info">
          <% if @booking.user == current_user %>
          <!-- render the page for the user -->
            <%= render "booking-user" %>

          <% elsif @booking.parking.user == current_user %>
          <!-- render the page for a parking owner -->
            <%= render "booking-owner", {booking: @booking} %>

          <% end %>

        </div>

        <%= link_to 'back to your bookings', bookings_path, class: 'btn btn-info btn-block' %>


      </div>
    </div>
  </div>

</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
      <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <title>Rent your parking</title>
    <%= csrf_meta_tags %>
    <%= action_cable_meta_tag %>
    <%= stylesheet_pack_tag "map" %>
    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%= favicon_link_tag asset_path('favicon.png') %>
    <%#= stylesheet_pack_tag 'application', media: 'all' %> <!-- Uncomment if you import CSS in app/javascript/packs/application.js -->
  </head>
  <body id="<%= controller_name %>_<%= action_name %>">
    <%= render 'shared/navbar' %>
    <%= render 'shared/flashes' %>
    <%= yield %>
    <%= render 'shared/footer' %>
    <%= javascript_include_tag 'application' %>
    <%= javascript_pack_tag 'application' %>
    <%= javascript_pack_tag "map" %>
  </body>
</html>

app/views/pages/home.html.erb
<div class="banner">
  <div class="banner-content">
    <h3>tired of spending hours looking for a parking space?</h3>
    <h6><span class="accent-header">we have one for you!</span></h6>
      <%= form_tag parkings_path, method: :get do %>
        <%= text_field_tag :query,
        params[:query],
        class: "form-control",
        placeholder: "where would you like to park your car?"
         %>
    <% end %>
  </div>
</div>


<div class="container">
  <div class="row">

    <div class="parkings-messages">
      <div class="col-xs-12 col-md-10 col-md-offset-1">
        <h3>here are some super cool parking spaces you could book</h3>
        <h6><span class="accent-header">isn't it great?</span></h6>
      </div>
    </div>

  </div>

  <div class="row">

    <% @home_parkings.each do |parking| %>
      <div class="col-xs-12 col-md-6 col-lg-4">
        <%= link_to parking_path(parking) do %>
        <%# raise %>
          <div class="parking-card" style="background-image: url( <%= parking.photo %> )">
            <div class="card-header">
              <h6><%= parking.city %></h6>
              <p><%= parking.user.email %></p>
            </div>
          </div>
        <% end %> <!-- end of link -->
      </div>
    <% end %> <!-- end of loop in the parkings -->


  </div>

  <div class="row">
    <div class="col-xs-10 col-xs-offset-1 col-md-4 col-md-offset-4">
  <%= link_to 'see all parking spaces', parkings_path, class: 'btn btn-primary btn-block btn-cta' %>

    </div>
  </div>


</div>

<div id="cta-new-parking">

  <div class="container">
    <div class="row">

      <div class="parkings-messages">
        <div class="col-xs-12 col-md-8 col-md-offset-2">
          <h3>don't let your parking space get lonely</h3>
          <h6><span class="accent-header">rent it out now!</span></h6>
          <%= link_to 'add your parking space', new_parking_path, class: 'btn btn-primary btn-block btn-cta' %>
        </div>
      </div>

    </div>
  </div>

</div>

app/views/pages/test.html.erb
<div class="container">

  <div class="row">

    <h1>this is a h1 title</h1>

    <h2>this is a h2 title</h2>

    <h3>this is the page title</h3>

    <h4>this is a h4 title</h4>

    <h5>this is a h5 title</h5>

    <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Necessitatibus inventore veritatis quidem ipsa eum ducimus voluptate. Qui tempora earum, aliquid dicta minus odit ea doloremque, modi vel officia aut soluta. Lorem ipsum dolor sit amet, consectetur adipisicing elit. <a href="#">here we would have a link</a> Necessitatibus inventore veritatis quidem ipsa eum ducimus voluptate. Qui tempora earum, aliquid dicta minus odit ea doloremque, modi vel officia aut soluta. Lorem ipsum dolor sit amet, consectetur adipisicing elit. </p>

    <p class="accent-text">
      this would be an accent text
    </p>

  </div>

</div>

app/views/parkings/_form.html.erb
<div id="new-parking-form">
  <!-- New parking Space Proposal -->
    <div class="col-xs-12 col-sm-6 col-sm-offset-3 col-md-4 col-md-offset-4">
      <%= simple_form_for(@parking) do |f| %>
          <%= f.input :address %>
          <%= f.input :description %>
          <%= f.input :price %>
          <%= f.input :city %>
          <%= f.input :start_time, as: :datepicker %>
          <%= f.input :finish_time, as: :datepicker %>
          <%= f.input :photo %>
          <%= f.input :photo_cache, as: :hidden %>

          <%= f.submit class: 'btn btn-primary' %>
      <% end %>
      <%#= link_to "Back", root_path, class:'btn btn-primary' %>
    </div>

</div>

app/views/parkings/_map_window_index.html.erb
<%= parking.description %>

app/views/parkings/_map_window_show.html.erb
<%= @parking.description %>

app/views/parkings/create.html.erb
<h1>Parkings#create</h1>
<p>Find me in app/views/parkings/create.html.erb</p>

app/views/parkings/edit.html.erb
<div class="container">
  <div class="row">
      <h3>you're updating your <%= @parking.address %> parking space </h3>
      <%= render "form" %>
  </div>
</div>

app/views/parkings/index.html.erb
<div class="container">
  <% if @parkings.count == 0 %>
    <h3>seems that there is no parking space here yet.</h3>
    <h6><span class="accent-header">that's super sad, we're sorry.</span></h6>
    <%= link_to "maybe you can take the metro instead?", "http://www.stm.info/fr"  %>
  <% elsif @parkings.count == 1 %>
    <h3>lucky you, there is one parking space waiting for you.</h3>
    <h6><span class="accent-header">don't wait too much to book it!</span></h6>
    <div class="row">
      <% @parkings.each do |parking| %>
        <div class="col-xs-12">
          <%= link_to parking_path(parking), class: 'parking-image' do %>
            <div class="parking-card">
              <%= parking.description[0] %>
              <%= parking.address %>
              <%= parking.city %>
            </div>
          <% end %>
        </div>
      <% end %>
    </div>
    <div id="map" style="width: 100%; height: 600px;" data-markers="<%= @markers.to_json %>"></div>
  <% else %>
    <h3>look at all the available parking spaces.</h3>
    <h6><span class="accent-header">there is one for you!</span></h6>
    <div class="row"><%= render "shared/parking-card" %></div>
    <div id="map" style="width: 100%; height: 600px;" data-markers="<%= @markers.to_json %>"></div>
  <% end %>
</div>

app/views/parkings/new.html.erb
<div class="container">
  <div class="row">
    <% if user_signed_in? %>
      <div class='text-center'>
        <h3>don't let your parking space get lonely</h3>
        <h6><span class="accent-header">and make money out of it.</span></h6>
      </div>
      <!-- links to form: New parking Space Proposal -->
      <%= render "form" %>
    <% else %>
      <!-- a user can go back to Home page without adding a parking space -->
      <!-- can change link path as needed -->
      <%= link_to "Login", new_user_session_path %>
    <% end %>
  </div>
</div>

app/views/parkings/show.html.erb
<div class="container-fluid">

  <div class="parking-title">
    <h3>beautiful parking space in
      <% if @parking.city.nil? %>
        Montréal
      <% else %>
        <%= @parking.city %>
      <% end %>
      </h3>
  </div>

  <div class="parking-content">

    <div class="parking-description">

      <div class="main-details">
        <h6><span class="booking">address:</span></h6>
        <p><%= @parking.address %></p>

        <h6><span class="booking">owned by:</span></h6>
        <p><%= @parking.user.email.split('@')[0] %></p>

        <h6><span class="booking">description: </span></h6>

        <p><%= @parking.description %></p>
      </div> <!-- end of main-details -->

      <div id="parking-calendar">

        <h6><span class="booking">availability:</span></h6>

        <%= calendar start_date: @parking.start_time, number_of_days: ((@parking.finish_time - @parking.start_time).to_f/86400).ceil, events: @parking.bookings do |date, bookings| %>
          <%= date.day %>
          <% bookings.each do |booking| %>
            <p>x</p>
          <% end %>
        <% end %>

      </div>

      <div class="parking-actions">
        <% if policy(@parking).edit? && policy(@parking).destroy? %>
        <ul>
          <%= link_to 'edit', edit_parking_path(@parking), class: 'btn btn-info' %>
          <%= link_to 'delete', parking_path(@parking), method: :delete, class: 'btn btn-info' %>
        </ul>
          <%= link_to 'see all the bookings for this space', '#', class: 'btn btn-info' %>
          <% else %>
            <%= simple_form_for([@parking, @booking]) do |f| %>
            <%= f.input :start_time, label: "start date", as: :datepicker  %>
            <%= f.input :finish_time, label: "end date", as: :datepicker%>

            <%= f.submit class: 'btn btn-light full-width', value: "Book now" %>
            <% end %>
        <% end %>
      </div> <!-- end of parking-actions -->


      <div class="parking-image">
        <% if @parking.photo.nil?  %>
          <%= image_tag "http://bit.ly/2PUFPFK" %>
        <% else %>
          <%= cl_image_tag @parking.photo, crop: :fill %>
        <% end %>
      </div> <!-- end of parking-image-->

    </div> <!-- end of parking-description -->

    <div id="map-wrapper">
      <div
        id="map-show"
        data-marker="<%= @marker.to_json %>"
      ></div>
    </div>


  </div> <!-- end of parking content -->


</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<div id="footer">
  <p> <span> <i class="fas fa-car"></i> created with mucho love, by the 188's finest people <i class="fas fa-car"></i> </span></p>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar-wagon">
  <!-- Logo -->
  <%= link_to root_path, class: "navbar-wagon-brand" do %>
    <i><i class="fas fa-car"></i></i>
  <% end %>

  <div id="navbar-search">
    <%= form_tag parkings_path, method: :get do %>
      <%= text_field_tag :query,
      params[:query],
      class: "form-control",
      placeholder: "find a parking space"
       %>
    <% end %>
  </div>

  <!-- Right Navigation -->
  <div class="navbar-wagon-right hidden-xs hidden-sm">

    <% if user_signed_in? %>

      <!-- Links when logged in -->
      <%= link_to "Spaces", parkings_path, class: "navbar-wagon-item navbar-wagon-link" %>
      <%= link_to "Bookings", bookings_path, class: "navbar-wagon-item navbar-wagon-link" %>
      <%= link_to "Add a parking space", new_parking_path, class: "navbar-wagon-item navbar-wagon-link" %>

      <!-- Avatar with dropdown menu -->
      <div class="navbar-wagon-item">
        <div class="dropdown">
          <%= image_tag "user-avatar.svg", class: "avatar dropdown-toggle", id: "navbar-wagon-menu", "data-toggle" => "dropdown" %>
          <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
            <li>
              <%= link_to "#" do %>
                <i class="fa fa-user"></i> <%= t(".profile", default: "Profile") %>
              <% end %>
            </li>
            <li>
              <%= link_to "#" do %>
                <i class="fa fa-cog"></i>  <%= t(".settings", default: "Settings") %>
              <% end %>
            </li>
            <li>
              <%= link_to destroy_user_session_path, method: :delete do %>
                <i class="fa fa-sign-out"></i>  <%= t(".sign_out", default: "Log out") %>
              <% end %>
            </li>
          </ul>
        </div>
      </div>
    <% else %>
      <!-- Login link (when logged out) -->
      <%= link_to t(".sign_in", default: "Login"), new_user_session_path, class: "navbar-wagon-item navbar-wagon-link" %>
    <% end %>
  </div>

  <!-- Dropdown list appearing on mobile only -->
  <div class="navbar-wagon-item hidden-md hidden-lg">
    <div class="dropdown">
      <i class="fa fa-bars dropdown-toggle" data-toggle="dropdown"></i>
      <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
        <li><a href="#">Some mobile link</a></li>
        <li><a href="#">Other one</a></li>
        <li><a href="#">Other one</a></li>
      </ul>
    </div>
  </div>
</div>

app/views/shared/_parking-card.html.erb
<% @parkings.each do |parking| %>

  <div class="col-xs-12 col-md-6 col-lg-4">
    <%#= link_to parking_path(parking), class: 'parking-image' do %>
      <div class="parking-card">

        <div class="parking-header">
          <p>
            <span class="parking-tags">residential</span>
            <span class="parking-tags">daytime</span>
            <span class="parking-tags">verified</span>
          </p>
          <p><%= parking.city %></p>
        </div> <!-- end of parking header -->

        <div class="parking-details">

          <div class="parking-user">
            <h6>owned by: <%= parking.user.email %></h6>
            <p><%= parking.price.floor %>$/day</p>
            <i class="fas fa-star"></i><i class="fas fa-star"></i>
          </div> <!-- end of parking user -->

          <div class="parking-more">
            <%= link_to parking_path(parking) do %>
            <i class="fas fa-plus-circle"></i>
            <% end %>
          </div> <!-- end of parking more -->

        </div> <!-- end of parking details -->

      </div>
    <%# end %> <!-- end of link -->
  </div> <!-- end of col classes -->

<% end %> <!-- end of loop in the array -->